# 1 Import from pkl files

In [13]:
import joblib
import matplotlib.pyplot as plt

df_sales = joblib.load('df_sales_silver.pkl')
df_product = joblib.load('df_product_silver.pkl')
df_cities = joblib.load('df_cities_silver.pkl')
df_forecast_revenue = joblib.load('df_forecast_revenue_silver.pkl')

# 2 Joining data

In [14]:
import pandas as pd

# Join the dataframes on the 'store_id' column
df_sales = pd.merge(df_sales, df_cities, on='store_id')

In [15]:
df_sales

,ID,store_id,product_id,date,sales,revenue,stock,price,promo_type_1,promo_bin_1,promo_type_2,promo_bin_2,promo_discount_2,promo_discount_type_2,storetype_id,store_size,city_id_old,country_id,city_code
0,1,S0002,P0001,2017-01-02,0.0,0.00,8.0,6.25,PR14,No promo bin 1,PR03,No promo bin 2,0.0,0,ST04,39,C007,TURKEY,Adana
1,2,S0002,P0005,2017-01-02,0.0,0.00,11.0,33.90,PR14,No promo bin 1,PR03,No promo bin 2,0.0,0,ST04,39,C007,TURKEY,Adana
2,3,S0002,P0011,2017-01-02,0.0,0.00,9.0,49.90,PR14,No promo bin 1,PR03,No promo bin 2,0.0,0,ST04,39,C007,TURKEY,Adana
3,4,S0002,P0015,2017-01-02,1.0,2.41,19.0,2.60,PR14,No promo bin 1,PR03,No promo bin 2,0.0,0,ST04,39,C007,TURKEY,Adana
4,5,S0002,P0017,2017-01-02,0.0,0.00,12.0,1.49,PR14,No promo bin 1,PR03,No promo bin 2,0.0,0,ST04,39,C007,TURKEY,Adana
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8818108,8885578,S0143,P0676,2019-10-24,0.0,0.00,0.0,19.90,PR03,verylow,PR03,No promo bin 2,0.0,0,ST03,13,C014,TURKEY,Istanbul
8818109,8885579,S0143,P0680,2019-10-24,0.0,0.00,0.0,139.90,PR14,No promo bin 1,PR03,No promo bin 2,0.0,0,ST03,13,C014,TURKEY,Istanbul
8818110,8885580,S0143,P0694,2019-10-24,0.0,0.00,0.0,7.50,PR14,No promo bin 1,PR03,No promo bin 2,0.0,0,ST03,13,C014,TURKEY,Istanbul
8818111,8885581,S0143,P0718,2019-10-24,0.0,0.00,0.0,23.75,PR14,No promo bin 1,PR03,No promo bin 2,0.0,0,ST03,13,C014,TURKEY,Istanbul
8818112,8885582,S0143,P0747,2019-10-24,0.0,0.00,0.0,21.90,PR14,No promo bin 1,PR03,No promo bin 2,0.0,0,ST03,13,C014,TURKEY,Istanbul

### 2.1 Check the last 7 days, because it needs to be removed prior to data trasnform

### 2.2 Create the pipeline and apply the transformation

### Add in temporary files to be possible use that in the following notebooks

In [16]:
import joblib

joblib.dump(df_sales, 'df_sales_golden.pkl')
joblib.dump(df_cities, 'df_cities_golden.pkl')
joblib.dump(df_product, 'df_product_golden.pkl')
joblib.dump(df_forecast_revenue, 'df_forecast_revenue_golden.pkl')

['df_forecast_revenue_golden.pkl']