In [1]:
# packages gerais
import pandas as pd
import joblib

# df_sales_ dataset
df_sales_filtered_all = joblib.load('df_sales_filtered_all.pkl')
df_sales_filtered_2018_2019 = joblib.load('df_sales_filtered_2018_2019.pkl')
df_sales_filtered_2019 = joblib.load('df_sales_filtered_2019.pkl')
df_sales_filtered_last_6_month = joblib.load('df_sales_filtered_last_6_month.pkl')

## 1 Create a date field based in Year and Week of the year

### 1.1 But the date to make sense should be the last day in that specific week

In [2]:
import datetime
# Function to get the last day of the week using ISO calendar
def get_last_day_of_iso_week(year, week):
    first_day_of_year = datetime.datetime(year, 1, 4)  # 4th January is always in the first ISO week
    first_monday_of_year = first_day_of_year - datetime.timedelta(days=first_day_of_year.weekday())
    week_start_date = first_monday_of_year + datetime.timedelta(weeks=week-1)
    return week_start_date + datetime.timedelta(days=6)

# Applying function to DataFrame
df_sales_filtered_last_6_month['last_day_of_week'] = df_sales_filtered_last_6_month.apply(
    lambda x: get_last_day_of_iso_week(x['year'], x['week']), axis=1
)

In [3]:
df_sales_filtered_last_6_month[(df_sales_filtered_last_6_month['store_id'] == 'S0097') & (df_sales_filtered_last_6_month['product_id'] == 'P0704')].tail(30)

,store_id,product_id,year,week,sales,revenue,stock,price,last_day_of_week
39826,S0097,P0704,2019,14,6.0,18.89,39.0,3.40,2019-04-07
39827,S0097,P0704,2019,15,4.0,12.60,35.0,3.40,2019-04-14
39828,S0097,P0704,2019,16,20.0,47.85,15.0,3.40,2019-04-21
39829,S0097,P0704,2019,17,15.0,33.04,20.0,3.40,2019-04-28
39830,S0097,P0704,2019,18,13.0,33.36,47.0,3.40,2019-05-05
39831,S0097,P0704,2019,19,7.0,15.75,37.0,3.40,2019-05-12
39832,S0097,P0704,2019,20,5.0,12.60,32.0,3.40,2019-05-19
39833,S0097,P0704,2019,21,3.0,9.45,29.0,3.40,2019-05-26
39834,S0097,P0704,2019,22,9.0,22.66,20.0,3.40,2019-06-02
39835,S0097,P0704,2019,23,4.0,8.81,16.0,3.40,2019-06-09
39836,S0097,P0704,2019,24,5.0,11.02,51.0,3.40,2019-06-16
39837,S0097,P0704,2019,25,25.0,55.09,26.0,3.40,2019-06-23
39838,S0097,P0704,2019,26,11.0,28.02,15.0,3.40,2019-06-30
39839,S0097,P0704,2019,27,1.0,3.15,14.0,3.40,2019-07-07
39840,S0097,P0704,2019,28,0.0,0.00,14.0,3.40,2019-07-14
39841,S0097,P0704,2019,29,3.0,9.45,11.0,3.40,2019-07-21
39842,S0097,P0704,2019,30,2.0,6.30,9.0,3.40,2019-07-28
39843,S0097,P0704,2019,31,17.0,41.24,52.0,3.40,2019-08-04
39844,S0097,P0704,2019,32,24.0,52.89,28.0,3.40,2019-08-11
39845,S0097,P0704,2019,33,6.0,18.90,42.0,3.40,2019-08-18
39846,S0097,P0704,2019,34,8.0,28.74,31.0,3.95,2019-08-25
39847,S0097,P0704,2019,35,1.0,3.66,30.0,3.95,2019-09-01
39848,S0097,P0704,2019,36,2.0,7.32,25.0,3.95,2019-09-08
39849,S0097,P0704,2019,37,6.0,21.94,19.0,3.95,2019-09-15
39850,S0097,P0704,2019,38,2.0,7.32,17.0,3.95,2019-09-22
39851,S0097,P0704,2019,39,7.0,25.61,10.0,3.95,2019-09-29

### 1.2 Convert date to time series by set as index and sort that

In [4]:
# Set 'date' column as index and sort by date
df_sales_filtered_last_6_month.set_index('last_day_of_week', inplace=True)
df_sales_filtered_last_6_month.sort_index(inplace=True)

In [5]:
df_sales_filtered_last_6_month

,store_id,product_id,year,week,sales,revenue,stock,price
last_day_of_week,,,,,,,,
2019-04-07,S0020,P0001,2019,14,2.0,18.56,9.0,10.95
2019-04-07,S0085,P0548,2019,14,39.0,86.67,79.0,1.95
2019-04-07,S0062,P0022,2019,14,1.0,60.45,9.0,101.90
2019-04-07,S0020,P0137,2019,14,0.0,0.00,16.0,56.90
2019-04-07,S0062,P0026,2019,14,2.0,9.16,6.0,4.95
...,...,...,...,...,...,...,...,...
2019-09-29,S0085,P0709,2019,39,88.0,567.07,287.0,7.00
2019-09-29,S0085,P0711,2019,39,0.0,0.00,56.0,12.90
2019-09-29,S0026,P0508,2019,39,1.0,6.02,12.0,6.50
2019-09-29,S0026,P0517,2019,39,0.0,0.00,3.0,199.95
2019-09-29,S0097,P0748,2019,39,1.0,17.50,8.0,18.90

### 1.3 Prepare to apply ARIMA

In [6]:
# Group by 'store_id' and 'product_id'
grouped = df_sales_filtered_last_6_month.groupby(['store_id', 'product_id'])

# Create a DataFrame to store forecasts and a data frame to have those product/store with error
df_forecasts = pd.DataFrame(columns=['store_id', 'product_id', 'forecast_week_1', 'forecast_week_2', 'forecast_week_3', 'ARIMA'])
df_product_error = pd.DataFrame(columns=['store_id', 'product_id', 'error_message'])

In [10]:
from statsmodels.tsa.arima.model import ARIMA
import warnings
from itertools import product

# Function to perform grid search for ARIMA parameters
def optimize_arima(series, p_values, d_value, q_values):
    best_aic = float("inf")
    best_order = None
    best_model = None
    for p, q in product(p_values, q_values):
        try:
            model = ARIMA(series, order=(p, d_value, q))
            model_fit = model.fit()
            aic = model_fit.aic
            if aic < best_aic:
                best_aic = aic
                best_order = (p, d_value, q)
                best_model = model_fit
        except:
            continue
    return best_order, best_model



# Grid search parameters
p_values = range(0, 3)
d_value  = 1
q_values = range(0, 3)

# Iterate over each group
for (store_id, product_id), group in grouped:
    # Reindex to ensure complete weekly intervals
    group = group.asfreq('W-SUN', method='pad')
    
    # Ensure there are enough data points to fit the model
    if len(group) < 2:
        df_product_error = pd.concat([df_product_error, pd.DataFrame([{
            'store_id': store_id,
            'product_id': product_id,
            'error_message': 'Not enough data points to fit ARIMA model'
        }])], ignore_index=True)
        continue
    
    warnings.filterwarnings("ignore")  # specify to ignore warning messages

    # Fit ARIMA model
    try:
       best_order, best_model = optimize_arima(group['sales'], p_values, d_value, q_values)
       
       if best_model is not None:
            # Forecast future sales (next 3 weeks)
            forecast = best_model.forecast(steps=3)
            
            # Append the forecast to the DataFrame
            df_forecasts = pd.concat([df_forecasts, pd.DataFrame([{
                'store_id': store_id,
                'product_id': product_id,
                'forecast_week_1': forecast[0],
                'forecast_week_2': forecast[1],
                'forecast_week_3': forecast[2],
                'ARIMA': best_order
            }])], ignore_index=True)
       else:
            df_product_error = pd.concat([df_product_error, pd.DataFrame([{
                'store_id': store_id,
                'product_id': product_id,
                'error_message': 'Failed to find suitable ARIMA model'
            }])], ignore_index=True)
    except Exception as e:
        print(f"Error fitting ARIMA for Store: {store_id}, Product: {product_id}")
        print(str(e))
        df_product_error = pd.concat([df_product_error, pd.DataFrame([{
            'store_id': store_id,
            'product_id': product_id,
            'error_message': str(e)
        }])], ignore_index=True)

Error fitting ARIMA for Store: S0020, Product: P0053
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0020, Product: P0104
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0020, Product: P0270
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0020, Product: P0415
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0020, Product: P0460
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0020, Product: P0523
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0020, Product: P0575
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0020, Product: P0581
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0020, Product: P0696
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0026, Product: P0119
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0026, Product: P0176
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0026, Product: P0270
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0026, Product: P0460
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0026, Product: P0581
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0062, Product: P0053
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0062, Product: P0104
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0062, Product: P0223
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0062, Product: P0270
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0062, Product: P0354
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0062, Product: P0411
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0062, Product: P0460
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0062, Product: P0634
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0085, Product: P0053
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0085, Product: P0071
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0085, Product: P0158
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0085, Product: P0270
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0085, Product: P0354
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0085, Product: P0460
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0085, Product: P0522
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0085, Product: P0576
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0085, Product: P0634
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0097, Product: P0001
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0097, Product: P0104
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0097, Product: P0132
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0097, Product: P0201
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0097, Product: P0270
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0097, Product: P0460
too many indices for array: array is 0-dimensional, but 1 were indexed
Error fitting ARIMA for Store: S0097, Product: P0646
too many indices for array: array is 0-dimensional, but 1 were indexed

In [8]:
# Save the forecast DataFrame and the error DataFrame to CSV files
df_forecasts.to_csv('./Files/last_6_month_forecasts.csv', index=False)
df_product_error.to_csv('./Files/last_6_month_forecast_errors.csv', index=False)

In [11]:
df_forecasts

     store_id product_id  forecast_week_1  forecast_week_2  forecast_week_3
0       S0020      P0001         3.679591         3.076388         2.966807
1       S0020      P0005         0.077732         0.074156         0.074320
2       S0020      P0007         0.008970         0.013976         0.016769
3       S0020      P0008         0.061070         0.091138         0.105941
4       S0020      P0009         2.034939         1.666881         1.733451
...       ...        ...              ...              ...              ...
3753    S0097      P0739         4.254362         4.221518         4.221771
3754    S0097      P0740         0.655014         0.680123         0.681085
3755    S0097      P0741         0.523572         0.486703         0.489299
3756    S0097      P0747        14.840114        15.060922        15.064444
3757    S0097      P0748         0.787388         1.215208         1.158235

[3758 rows x 5 columns]